version: '3'

volumes:
  dbdata:
    driver: local

services:

### APP: Application server #########################################
    app:
      build:
        context: ./
        dockerfile: docker/app/Dockerfile
        args:
          - DOCKER_APP_UID=${DOCKER_APP_UID:-1000}
      working_dir: /var/www
      volumes:
        - ./:/var/www
      environment:
        DB_HOST: mysql
        #REDIS_HOST: redis
      ports:
        - "9000:9000"
      depends_on:
        - database

### WEB: Web server #################################################
    web:
      build:
        context: ./
        dockerfile: docker/web/Dockerfile
        args:
          - DOCKER_APP_UID=${DOCKER_APP_UID:-1000}
      volumes:
        - ./:/var/www:ro
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - app

### MYSQL: Database server #######################################
    mysql:
      image: mysql:5
      volumes:
            - dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: 'laravel'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      ports:
        - "3306:3306"

### REDIS: Redis server #############################################
#    redis:
#      image: redis:5
#      ports:
#        - "6379:6379"

### MAILHOG: Redis server #############################################
#    mailhog:
#      image: mailhog/mailhog:latest
#      ports:
#        - "1025:1025"
#        - "8025:8025"
